import bcrypt from 'bcryptjs';

const data = {

    users: [
        {
            name: 'Basir',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],

    products: [
        {
            // _id: '1',
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: 'images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality cloth',
        },
        {
            // _id: '2',
            name: 'Adidas Fit Shirt',
            slug: 'adidas-fit-shirt',
            category: 'Shirts',
            image: 'images/p2.jpg',
            price: 250,
            countInStock: 10,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality cloth',
        },
        {
            // _id: '3',
            name: 'Nike Slim Pant',
            slug: 'nike-slim-pant',
            category: 'Pants',
            image: 'images/p3.jpg',
            price: 250,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 40,
            description: 'high quality cloth',
        },
        {
            // _id: '4',
            name: 'Adidas Loose Shirt',
            slug: 'adidas-loose-shirt',
            category: 'Shirt',
            image: 'images/p4.jpg',
            price: 165,
            countInStock: 10,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality cloth',
        },
        {
            // _id: '5',
            name: 'Wild Silk Cloth',
            slug: 'wild-silk-cloth',
            category: 'Shirt',
            image: 'images/p5.jpg',
            price: 300,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 40,
            description: 'high quality cloth',
        },
        {
            // _id: '6',
            name: 'Cozy Silk\'s Sweater',
            slug: 'cozy-silks-sweater',
            category: 'Sweater',
            image: 'images/p8.jpg',
            price: 250,
            countInStock: 10,
            brand: 'Nike',
            rating: 5,
            numReviews: 20,
            description: 'high quality cloth',
        },
        {
            // _id: '7',
            name: 'Extreme Cotton Webber',
            slug: 'extreme-cotton-webber',
            category: 'Jacket',
            image: 'images/p10.jpg',
            price: 170,
            countInStock: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 40,
            description: 'high quality cloth',
        },
        {
            // _id: '8',
            name: 'Long Sleeveless Dickeys Shirt',
            slug: 'long-sleeveless-dickeys-shirt',
            category: 'Long Sleeve',
            image: 'images/p11.jpg',
            price: 170,
            countInStock: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 40,
            description: 'high quality cloth',
        },


    ],
};

export default data;